DELETE FROM users WHERE name = 'John Doe';


ALTER TABLE users ADD COLUMN email TEXT NOT NULL UNIQUE;
ALTER TABLE users ADD COLUMN age INT NOT NULL DEFAULT 0 CHECK (age >= 0);
ALTER TABLE users ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT NOW();